; Auto-Generated by Nux High-Level Compiler (Kernel)
JMP __start_execution
; Implicit main function
JMP skip___main
__main:
PUSH 35
PUSH 0
POKE
PUSH 0
PEEK
PRINT_VAL
PUSH 10
PRINT_CHAR
PUSH 0
RET
skip___main:
__start_execution:
CALL __main 0
POP
EXIT
