; Auto-Generated by Nux High-Level Compiler (Kernel)
JMP __start_execution
; Function MyClass_test2
JMP skip_MyClass_test2
MyClass_test2:
OP_GET_LOCAL 0
PUSH 0
OP_ADD
PUSH 20
POKE
PUSH 0
RET
skip_MyClass_test2:
; Function MyClass_test
JMP skip_MyClass_test
MyClass_test:
OP_GET_LOCAL 0

PUSH 0
OP_ADD
PEEK
PUSH 10
EQ
PUSH 0
JE __if_else_0
OP_GET_LOCAL 0
CALL MyClass_test2 1
POP
JMP __if_end_0
__if_else_0:
__if_end_0:
PUSH 0
RET
skip_MyClass_test:
; Implicit main function
JMP skip___main
__main:
PUSH 1
PUSH 1
OP_IMG_ALLOC
PUSH 0
SWAP
POKE
PUSH 0
PEEK
CALL MyClass_test 1
POP
PUSH 0
RET
skip___main:
__start_execution:
CALL __main 0
POP
EXIT
