; Auto-Generated by Nux High-Level Compiler (Kernel)
JMP __start_execution
; Function main
JMP skip_main
main:
PUSH 10
PUSH 20
CALL max 2
OP_GET_LOCAL 0

PRINT_VAL
PUSH 0
RET
skip_main:
; Implicit main function
JMP skip___main
__main:
CALL main 0
POP
PUSH 0
RET
skip___main:
__start_execution:
CALL __main 0
POP
EXIT
