use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Deserialize, Serialize)]
pub struct BonfortConfig {
    pub package: PackageMetadata,
    #[serde(default)]
    pub dependencies: HashMap<String, String>,
    #[serde(default, rename = "dev-dependencies")]
    pub dev_dependencies: HashMap<String, String>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PackageMetadata {
    pub name: String,
    pub version: String,
    #[serde(default)]
    pub authors: Vec<String>,
    #[serde(default)]
    pub edition: String,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct BonfortLock {
    #[serde(rename = "package")]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

impl BonfortConfig {
    pub fn from_file(path: &Path) -> Result<Self, String> {
        let contents = fs::read_to_string(path)
            .map_err(|e| format!("Failed to read Bonfort.toml: {}", e))?;
        
        toml::from_str(&contents)
            .map_err(|e| format!("Failed to parse Bonfort.toml: {}", e))
    }

    pub fn to_file(&self, path: &Path) -> Result<(), String> {
        let contents = toml::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize Bonfort.toml: {}", e))?;
        
        fs::write(path, contents)
            .map_err(|e| format!("Failed to write Bonfort.toml: {}", e))
    }

    pub fn add_dependency(&mut self, name: String, version: String) {
        self.dependencies.insert(name, version);
    }

    pub fn remove_dependency(&mut self, name: &str) -> bool {
        self.dependencies.remove(name).is_some()
    }
}

impl BonfortLock {
    pub fn new() -> Self {
        BonfortLock {
            packages: Vec::new(),
        }
    }

    pub fn from_file(path: &Path) -> Result<Self, String> {
        let contents = fs::read_to_string(path)
            .map_err(|e| format!("Failed to read Bonfort.lock: {}", e))?;
        
        toml::from_str(&contents)
            .map_err(|e| format!("Failed to parse Bonfort.lock: {}", e))
    }

    pub fn to_file(&self, path: &Path) -> Result<(), String> {
        let mut contents = String::from("# Generated by bonfort\n# Do not edit manually\n\n");
        contents.push_str(&toml::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize Bonfort.lock: {}", e))?);
        
        fs::write(path, contents)
            .map_err(|e| format!("Failed to write Bonfort.lock: {}", e))
    }

    pub fn add_package(&mut self, package: LockedPackage) {
        // Remove existing entry if present
        self.packages.retain(|p| p.name != package.name);
        self.packages.push(package);
    }

    pub fn get_package(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }
}

// Version resolution helpers
pub fn resolve_version(version_req: &str, available: &str) -> bool {
    // Simple version matching for now
    // TODO: Implement proper semver resolution
    match version_req {
        "*" => true,
        v if v.starts_with('^') => {
            // ^0.3 means >=0.3.0, <0.4.0
            let req = v.trim_start_matches('^');
            available.starts_with(req)
        }
        v if v.starts_with('~') => {
            // ~1.2 means >=1.2.0, <1.3.0
            let req = v.trim_start_matches('~');
            available.starts_with(req)
        }
        v => v == available,
    }
}
