#![no_std]
#![no_main]

use esp_backtrace as _;
use esp_hal::{delay::Delay, prelude::*};
use nux_embedded::{NuxEmbeddedVm, hal::esp32::Esp32Hal};

// Embedded bytecode (will be generated by compiler)
// This is a simple "blink LED" program
static BYTECODE: &[u8] = include_bytes!("../blink.nuxi");

#[entry]
fn main() -> ! {
    let peripherals = esp_hal::init(esp_hal::Config::default());
    
    let delay = Delay::new();
    let hal = Esp32Hal::new(delay);
    
    let mut vm = NuxEmbeddedVm::new(BYTECODE, hal);
    
    esp_println::println!("Nux Embedded VM Starting...");
    
    match vm.run() {
        Ok(_) => esp_println::println!("Program completed successfully"),
        Err(e) => esp_println::println!("Runtime error: {}", e),
    }
    
    loop {
        // Halt
    }
}
